In [1]:
# imports
import pandas as pd
import requests
import yfinance as yf
import numpy as np
from transformers import pipeline
from datetime import datetime, timedelta
import finnhub
from dotenv import load_dotenv
import os
from edgar import Company, set_identity
import regex as re

### Gathering Data

In [2]:
headers = {"User-Agent": "Mozilla/5.0 (compatible; my-script/1.0)"}
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
html = requests.get(url, headers=headers).text
table = pd.read_html(html)[0]
table['Symbol'] = table['Symbol'].str.replace('.', '-').tolist()
table.head()

/var/folders/5l/vsm1wvjn4qdg25qwjfcj83kr0000gn/T/ipykernel_80956/4004594965.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  table = pd.read_html(html)[0]

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

#### Tickers
**Semiconductors**: NVDA (NVIDIA), AMD (Advanced Micro Devices), INTC (Intel), ASML (ASML Holding), TSM (Taiwan Semiconductor Manufacturing), AVGO (Broadcom), 
    MRVL (Marvell Technology), ARM (Arm Holdings), SMCI (Super Micro Computer)<br>
**Hyperscalers**: MSFT (Microsoft), GOOGL (Google), AMZN (Amazon), META (Facebook) <br>
**AI Pure Plays**: PLTR (Palantir), AI (C3.ai), SOUN (Soundhound AI) <br>
**Infrastructure**: DELL (Dell Technologies), ANET (Arista Networks), HPE (Hewlett Packard Enterprise)

In [3]:
# list of all the tickers with a dictionary that sorts them by type of stock
tickers = pd.read_csv('../../data/tickers.csv')
tickers = tickers.drop(columns=['Unnamed: 0'])

ai_tickers = {
    'semis':   ['NVDA','AMD','INTC','ASML','TSM','AVGO','MRVL','ARM','SMCI'], # semiconductors
    'hypers':  ['MSFT','GOOGL','AMZN','META'], # hyperscalar
    'pure':    ['PLTR','AI','SOUN'], # AI pure plays
    'infra':   ['DELL','ANET','HPE'] # infrastructure
}
all_tickers = [t for group in ai_tickers.values() for t in group]

In [4]:
# Data from 2018 - 2026 (pre-COVID to present)
prices = yf.download(
    tickers=all_tickers + ['SOXX', 'QQQ'],
    start='2018-01-01',
    end='2026-01-01',
    auto_adjust=True,
    progress=False
)
prices.to_csv('../../data/prices_raw.csv')

In [5]:
prices.head()

Price      Close                                                          \
Ticker        AI    AMD       AMZN       ANET ARM        ASML       AVGO
Date
2018-01-02   NaN  10.98  59.450500  14.439375 NaN  163.474457  21.053343
2018-01-03   NaN  11.55  60.209999  14.725000 NaN  164.716187  21.283577
2018-01-04   NaN  12.12  60.479500  14.543125 NaN  166.252197  21.290676
2018-01-05   NaN  11.88  61.457001  14.798125 NaN  168.202164  21.416830
2018-01-08   NaN  12.28  62.343498  15.691250 NaN  169.085205  21.468086

Price                                        ...    Volume                     \
Ticker           DELL      GOOGL        HPE  ...      META     MRVL      MSFT
Date                                         ...
2018-01-02  21.014692  53.188858  11.300009  ...  18151900  5619900  22483800
2018-01-03  21.236492  54.096313  11.369617  ...  16886600  9014000  26061400
2018-01-04  21.613804  54.306454  11.648057  ...  13880900  9221200  21912000
2018-01-05  21.771866  55.026566  11.640324  ...  13574500  5855400  23407100
2018-01-08  21.766768  55.220848  11.462428  ...  17994700  5529500  22113000

Price
Ticker           NVDA PLTR       QQQ     SMCI SOUN     SOXX      TSM
Date
2018-01-02  355616000  NaN  32573300  4344000  NaN  2860200  4984000
2018-01-03  914704000  NaN  29383600  4094000  NaN  1326900  6963200
2018-01-04  583268000  NaN  24776100  3631000  NaN  1335000  4876600
2018-01-05  580124000  NaN  26992300  2178000  NaN  1170600  5330800
2018-01-08  881216000  NaN  23159100  3484000  NaN  1622700  3538200

[5 rows x 105 columns]

### Cleaning Data

In [6]:
close  = prices['Close']
volume = prices['Volume']
soxx   = close['SOXX']
qqq    = close['QQQ']

In [7]:
# Remove tickers with more than 5% NaN values
clean_prices = close.loc[:, close.isna().mean() <= 0.05]

# Forward fill short gaps of 1-2 days
clean_prices = clean_prices.ffill(limit=2)
clean_prices = clean_prices.dropna()
clean_prices.to_csv('../../data/clean_prices.csv')

In [8]:
# Convert prices to log
log_ret = np.log(clean_prices / clean_prices.shift(1)).dropna()

### Feature Engineering

In [9]:
# SOXX: holds 30 largest semiconductor companies
# QQQ: holds 100 largest non-financial companies on the NASDAQ, heavily weighted towards big tech
def make_features(close: pd.Series,
                     volume: pd.Series,
                     soxx: pd.Series,
                     qqq: pd.Series) -> pd.DataFrame:
    df = pd.DataFrame(index=close.index)

    # Lag returns: percent change over x days
    for lag in [1, 3, 5, 10, 20]:
        df[f'ret_{lag}d'] = close.pct_change(lag)

    # Rolling volatility
    df['vol_5d']  = close.pct_change().rolling(5).std()
    df['vol_20d'] = close.pct_change().rolling(20).std()

    # RSI (14-day): Relative Strength Index; measures magnitude and recent price changes in stocks
    delta = close.pct_change()
    gain  = delta.clip(lower=0).rolling(14).mean()
    loss  = (-delta.clip(upper=0)).rolling(14).mean()
    df['rsi_14'] = 100 - (100 / (1 + gain / loss))

    # How does the stock compare to SOXX and QQQ?
    df['rel_soxx'] = close.pct_change(20) - soxx.pct_change(20)
    df['rel_qqq']  = close.pct_change(20) - qqq.pct_change(20)

    # Volume spike: number of shares traded on a given day
    df['vol_spike'] = volume / volume.rolling(20).mean()

    # 52-week high proximity: the highest price traded at over the last 252 trading days (1 year)
    df['pct_from_52wk_high'] = close / close.rolling(252).max() - 1

    return df.dropna()

In [10]:
all_feature_dfs = []
for ticker in all_tickers:
    if ticker not in close.columns:
        continue
    ticker_feats = make_features(
        close  = close[ticker],
        volume = volume[ticker],
        soxx   = soxx,
        qqq    = qqq
    )
    ticker_feats['Ticker'] = ticker      
    all_feature_dfs.append(ticker_feats)

In [11]:
features_df = pd.concat(all_feature_dfs).reset_index()
features_df = features_df.set_index(['Date','Ticker'])

In [12]:
# Forward 5-day cumulative return
features_df['fwd_5d'] = (
    features_df.groupby('Ticker')['ret_1d']
    .transform(lambda x: x.shift(-1).rolling(5).sum())
)

# Cross-sectional: top half = 1, bottom half = 0 (guaranteed 50/50 per date)
# Which stocks will outperform their peers? 
features_df['Target'] = (
    features_df.groupby('Date')['fwd_5d']
    .transform(lambda x: (x > x.median()).astype(int))
)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1241: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [13]:
features_df.head()

,,ret_1d,ret_3d,ret_5d,ret_10d,ret_20d,vol_5d,vol_20d,rsi_14,rel_soxx,rel_qqq,vol_spike,pct_from_52wk_high,fwd_5d,Target
Date,Ticker,,,,,,,,,,,,,,
2019-01-02,NVDA,0.020374,0.038499,0.071923,-0.051261,-0.166493,0.023554,0.034328,37.207817,-0.107088,-0.083557,0.785101,-0.528766,NaN,0
2019-01-03,NVDA,-0.060417,-0.042349,-0.038392,-0.128964,-0.247295,0.033031,0.034169,30.211021,-0.110360,-0.119161,1.104590,-0.557236,NaN,0
2019-01-04,NVDA,0.064067,0.020150,0.038271,-0.016750,-0.133155,0.045219,0.035031,40.655523,-0.080480,-0.078587,0.933377,-0.528870,NaN,0
2019-01-07,NVDA,0.052941,0.052709,0.072952,0.061436,-0.094068,0.049557,0.037384,48.847621,-0.063841,-0.044049,1.128762,-0.503928,NaN,0
2019-01-08,NVDA,-0.024896,0.092507,0.047415,0.079185,-0.052707,0.052560,0.034712,48.297100,-0.055655,-0.044009,1.240790,-0.516278,0.051363,1

In [14]:
features_df.to_csv('../../data/features_df.csv')

### 500 Most Recent News Sentiment with FinnHub

In [15]:
load_dotenv()

True

In [16]:
client = finnhub.Client(api_key=os.getenv("FINNHUB_API_KEY"))

In [17]:
# date, headline, and summary of most recent 500 news per ticker
def get_ai_news(ticker, start_date, end_date):
    articles = []
    news = client.company_news(ticker, _from=start_date, to=end_date)
    for item in news[:500]:
        articles.append({
            'date':     datetime.fromtimestamp(item['datetime']).date(),
            'headline': item['headline'],
            'summary':  item.get('summary', '')
        })
    return pd.DataFrame(articles)

In [18]:
finbert = pipeline('sentiment-analysis', model='ProsusAI/finbert', truncation=True, max_length=512)

Device set to use mps:0

In [ ]:
def clean_filing_text(text):
    text = re.sub(r'<[^>]+>', ' ', text)          # remove HTML tags
    text = re.sub(r'&[a-z]+;', ' ', text)          # remove HTML entities
    text = re.sub(r'\s+', ' ', text)               # normalize whitespace
    text = re.sub(r'\d{1,2}/\d{1,2}/\d{2,4}', '', text)  # remove dates
    text = re.sub(r'\$[\d,\.]+', '', text)         # remove dollar amounts
    text = re.sub(r"[’']", '', text)               # drop apostrophes (It's -> Its), no gap left behind
    text = re.sub(r'[^\w\s\.]', ' ', text)         # remove special characters
    # text = re.sub(r'\s+', ' ', text)               # normalize whitespace
    return text.strip()

In [20]:
def clean_headlines(text):
    text = re.sub(r'<[^>]+>', ' ', text)    # remove HTML tags
    text = re.sub(r'\s+', ' ', text)         # normalize whitespace
    text = re.sub(r'[^\w\s\.]', ' ', text)   # remove special characters
    return text.strip()

In [21]:
def score_headlines(df):
    texts = (df['headline'] + '. ' + df['summary']).tolist()
    results = finbert(texts)
    df['sentiment'] = [r['label'].lower() for r in results]
    df['score'] = [r['score'] if r['label'] == 'positive' else -r['score'] if r['label'] == 'negative' else 0 for r in results]
    daily = df.groupby('date').agg(
        news_sentiment = ('score', 'mean'),
        news_count = ('score', 'count'),
        pct_positive = ('sentiment', lambda x: (x=='positive').mean())
    )
    return daily

In [22]:
def get_sentiment_for_ticker(ticker, df_ticker):
    # find the beginning and end dates for each ticker
    start_date = df_ticker.index.get_level_values('Date').min().strftime("%Y-%m-%d")
    end_date   = df_ticker.index.get_level_values('Date').max().strftime("%Y-%m-%d")
    
    news_df = get_ai_news(ticker, start_date, end_date)
    if news_df.empty:
        return pd.DataFrame()
    
    # clean text
    news_df['headline'] = news_df['headline'].apply(clean_headlines)
    # news_df['summary'] = news_df['summary'].apply(clean_filing_text)
    
    # provides sentiment rating based on 500 most recent news for each ticker
    daily_sentiment = score_headlines(news_df)
    daily_sentiment['Ticker'] = ticker
    return daily_sentiment

In [23]:
# Loop over all tickers
all_sentiment = []
for ticker in features_df.index.get_level_values('Ticker').unique():
    df_ticker = features_df.xs(ticker, level='Ticker')
    sentiment = get_sentiment_for_ticker(ticker, df_ticker)
    if not sentiment.empty:
        all_sentiment.append(sentiment)

sentiment_df = pd.concat(all_sentiment)
sentiment_df.index = pd.to_datetime(sentiment_df.index)
sentiment_df.to_csv('../../data/sentiment_df.csv')

In [24]:
# merge sentiment df back to features df
df = features_df.reset_index()
df['Date'] = pd.to_datetime(df['Date'])
df = df.merge(
    sentiment_df.reset_index().rename(columns={'date': 'Date'}),
    on=['Date', 'Ticker'],
    how='left'
)
df = df.set_index(['Date', 'Ticker'])

# Fill missing sentiment (days with no news)
df[['news_sentiment', 'new_count', 'pct_positive']] = df[['news_sentiment', 'news_count', 'pct_positive']].fillna(0)

### SEC 8K Filings (Earnings Releases)

In [25]:
# Domain keyword dictionaries
NVIDIA_KEYWORDS = [
    'h100', 'h200', 'h20',
    'blackwell', 'b100', 'b200', 'gb200', 'gb300',
    'rubin', 'vera rubin', 'nvl72',
    'dgx', 'hgx',
    'cuda', 'tensorrt', 'triton', 'nim microservices',
    'hopper architecture', 'blackwell architecture',
    
]

AMD_KEYWORDS = [
    'instinct mi300', 'instinct mi300x', 'instinct mi325',
    'instinct mi350', 'instinct mi400',
    'instinct mi250', 'instinct mi200',
    'radeon pro', 'radeon instinct',
    'rocm', 'hip framework', 'amd cdna',
    'amd rdna', 'amd infinity fabric',
    'amd gpu demand', 'amd accelerator',
    'amd data center gpu', 'amd ai accelerator',
    'amd compute demand', 'amd inference',
    'amd training workload', 'amd cluster',
]

INTEL_KEYWORDS = [
    'gaudi2', 'gaudi 2', 'gaudi3', 'gaudi 3',
    'habana labs', 'habana gaudi',
    'ponte vecchio', 'max series gpu',
    'intel gpu max', 'flex series gpu',
    'openvino', 'intel oneapi', 'intel neural compressor',
    'intel xeon ai', 'intel core ultra ai',
    'meteor lake ai', 'lunar lake ai', 'arrow lake ai', 'intel npu',
    'intel data center gpu', 'intel ai accelerator',
    'intel compute demand', 'intel ai inference',
    'intel training workload', 'gaudi deployment', 'gaudi adoption', 'gaudi demand',
]

GENERAL_GPU_KEYWORDS = [
    'gpu demand', 'gpu supply', 'gpu allocation',
    'data center revenue', 'data center demand',
    'inference demand', 'inference workload',
    'training compute', 'compute demand',
    'cloud ai', 'ai infrastructure', 'ai accelerator',
    'tensor processing', 'custom ai chip',
]


CAPEX_UP_KEYWORDS = [
    'increasing capex', 'raised capex', 'accelerating capex',
    'accelerating investment', 'capital expenditure increase',
    'expanding capacity', 'record investment',
    'investing heavily', 'multiyear investment',
    'committed to investing', 'significant investment in ai',
    'capital investment', 'infrastructure investment', 'ai investment'
]

CAPEX_DOWN_KEYWORDS = [
    'reducing capex', 'cutting investment', 'slowing spend',
    'deferring investment', 'pausing investment',
    'capital efficiency', 'disciplined spending',
    'revisiting capex', 'moderating investment'
]

COMPETITIVE_RISK_KEYWORDS = [
    'amd instinct', 'gaudi', 'trainium', 'inferentia', 'maia',
    'google tpu', 'axion',
    'custom silicon', 'in-house chip', 'in-house ai chip',
    'merchant silicon', 'proprietary chip',
    'competitive alternative', 'alternative to nvidia',
    'amd alternative', 'nvidia alternative',
    'vendor diversification', 'multi vendor gpu',
]

In [26]:
def extract_domain_signals(transcript_text):
    text_lower = transcript_text.lower()
    signals = {}

    # Raw mention counts (normalize by transcript length)
    word_count = len(text_lower.split())
    signals['nvidia_mentions'] = sum(text_lower.count(k) for k in NVIDIA_KEYWORDS) / word_count * 1000
    signals['amd_mentions'] = sum(text_lower.count(k) for k in AMD_KEYWORDS) / word_count * 1000
    signals['intel_mentions'] = sum(text_lower.count(k) for k in INTEL_KEYWORDS) / word_count * 1000
    signals['gpu_mentions'] = sum(text_lower.count(k) for k in GENERAL_GPU_KEYWORDS) / word_count * 1000
    signals['capex_up_score']  = sum(text_lower.count(k) for k in CAPEX_UP_KEYWORDS) / word_count * 1000
    signals['capex_down_score']= sum(text_lower.count(k) for k in CAPEX_DOWN_KEYWORDS) / word_count * 1000
    competitor_keys = [k for k in COMPETITIVE_RISK_KEYWORDS if k != ticker.lower()]
    signals['competitor_mentions'] = sum(text_lower.count(k) for k in competitor_keys) / word_count * 1000
    signals['capex_net']       = signals['capex_up_score'] - signals['capex_down_score'] 

    # Paragraph-level: find sentences mentioning AI demand
    ai_sentences = [s for s in transcript_text.split('.')
                    if any(k in s.lower() for k in ['artificial intelligence','ai demand','ai revenue', 'ai growth', 'ai contribution'])]
    signals['ai_sentence_ratio'] = len(ai_sentences) / max(len(transcript_text.split('.')),1)

    return signals

In [27]:
load_dotenv()

True

In [28]:
set_identity(os.getenv('EMAIL'))

In [29]:
# get earnings transcript 
def get_earnings_transcripts(ticker):
    company = Company(ticker)
    filings = company.get_filings(form="8-K")
    
    results = []
    for filing in filings:
        try:
            # only earnings releases
            if '2.02' not in str(filing.items):
                continue
            
            for attachment in filing.attachments:
                if 'EX-99' not in attachment.document_type:
                    continue
                
                text = attachment.text()

                if not text or len(text) < 200:
                    continue
                
                text = clean_filing_text(text) # reuse cleaning text regex
                signals = extract_domain_signals(text)

                results.append({
                    'Ticker': ticker,
                    'Date': pd.to_datetime(filing.filing_date),
                    'Text': text,
                    **signals
                })
                break  # one exhibit per filing
                
        except Exception as e:
            print(f"Skipped {ticker} {filing.filing_date}: {e}")
            continue
    
    print(f"{ticker}: {len(results)} qualifying filings")
    return results

In [30]:
all_transcript_signals = []

for ticker in all_tickers:
    transcripts = get_earnings_transcripts(ticker)
    for t in transcripts:
        signals = extract_domain_signals(t['Text'])
        signals['Ticker'] = t['Ticker']
        signals['Date'] = t['Date']
        all_transcript_signals.append(signals)

transcript_signals_df = (pd.DataFrame(all_transcript_signals).set_index(['Date', 'Ticker']).sort_index())

transcript_signals_df.to_csv('../../data/transcript_signals_df.csv')
transcript_signals_df.head()

NVDA: 94 qualifying filings

AMD: 95 qualifying filings

INTC: 109 qualifying filings
ASML: 0 qualifying filings
TSM: 0 qualifying filings

AVGO: 34 qualifying filings

MRVL: 24 qualifying filings
ARM: 0 qualifying filings

SMCI: 101 qualifying filings

MSFT: 90 qualifying filings

GOOGL: 45 qualifying filings

AMZN: 88 qualifying filings

META: 57 qualifying filings

PLTR: 25 qualifying filings

AI: 26 qualifying filings

SOUN: 19 qualifying filings

DELL: 42 qualifying filings

ANET: 49 qualifying filings

HPE: 54 qualifying filings

                   nvidia_mentions  amd_mentions  intel_mentions  \
Date       Ticker
2004-10-07 AMD                 0.0           0.0             0.0
2004-10-12 INTC                0.0           0.0             0.0
2004-10-21 AMZN                0.0           0.0             0.0
           MSFT                0.0           0.0             0.0
2004-10-27 NVDA                0.0           0.0             0.0

                   gpu_mentions  capex_up_score  capex_down_score  \
Date       Ticker
2004-10-07 AMD              0.0             0.0               0.0
2004-10-12 INTC             0.0             0.0               0.0
2004-10-21 AMZN             0.0             0.0               0.0
           MSFT             0.0             0.0               0.0
2004-10-27 NVDA             0.0             0.0               0.0

                   competitor_mentions  capex_net  ai_sentence_ratio
Date       Ticker
2004-10-07 AMD                     0.0        0.0                0.0
2004-10-12 INTC                    0.0        0.0                0.0
2004-10-21 AMZN                    0.0        0.0                0.0
           MSFT                    0.0        0.0                0.0
2004-10-27 NVDA                    0.0        0.0                0.0

In [31]:
nvda_tickers = get_earnings_transcripts('NVDA')
nvda_tickers[0]

NVDA: 94 qualifying filings

{'Ticker': 'NVDA',
 'Date': Timestamp('2026-08-26 00:00:00'),

In [32]:
import textwrap
print(textwrap.fill(nvda_tickers[0]['Text'][:2000], width=100))

NVIDIA Announces Financial Results for Second Quarter Fiscal 2027   Revenue of  billion  up 106
from a year ago   Data Center revenue of  billion  up 117  from a year ago SANTA CLARA  Calif. Aug.
26  2026  NVIDIA  NASDAQ  NVDA  today reported revenue for the second quarter ended July 26  2026
of  billion  up 18  from the previous quarter and up 106  from a year ago. For the quarter  GAAP and
non GAAP gross margins were both 75.0 . GAAP and non GAAP earnings per diluted share were  and
respectively.  AI has reached its inflection point. Its doing useful work. Its tokens are productive
and profitable. Now  compute is revenue   said Jensen Huang  founder and CEO of NVIDIA.  And demand
is accelerating. This time last year  one lab alone was driving the buildout  today  we have a
golden age of new AI labs and startups  multiple frontier labs scaling in parallel  a thriving open
model ecosystem and physical AI coming online   with strong momentum across the U.S. and around the
world. The AI infrastructure buildout is at full steam. Vera Rubin  now in full production  was
built to power exactly this moment.  During the second quarter of fiscal 2027  NVIDIA returned
approximately  billion to shareholders in the form of shares repurchased and cash dividends. As of
the end of the second quarter  the company had approximately  billion remaining under its share
repurchase authorization. NVIDIA will pay its next quarterly cash dividend of  per share on October
1  2026  to all shareholders of record on September 10  2026. Q2 Fiscal 2027 Summary GAAP    in mill
exce  Q2 Q1 FY27 Q2 FY26 Q Q Y Y earn  FY27 per shar  Reve        18   106   Gross 75.0   74.9
72.4   0.1 pts 2.6 marg  pts Oper     10   55   expe  Oper        19   124   inco  Net       2   126
inco  Dilu  earn     3   128   per share Non G     in milli  except Q2 FY27 Q1 FY27 Q2 FY26 Q Q Y Y
earni  per share  Reven     18   106   Gross 75.0   75.0   72.5     2.5 pts margin Opera     11   54
expen  Opera     19

In [33]:
# merge back to original dataframe
df = df.reset_index()

df = pd.merge_asof(
    df.sort_values('Date'),
    transcript_signals_df.reset_index().rename(columns={'date': 'Date'}).sort_values('Date'),
    on='Date',
    by='Ticker',
    direction='backward'
)

with_domain_keywords = df.set_index(['Date', 'Ticker'])
with_domain_keywords[['gpu_mentions','capex_up_score','capex_down_score', 'capex_net','competitor_mentions','ai_sentence_ratio']] = \
    with_domain_keywords[['gpu_mentions','capex_up_score','capex_down_score', 'capex_net','competitor_mentions','ai_sentence_ratio']].fillna(0)

### Final Cleaning

In [34]:
edgar_cols = ['gpu_mentions', 'capex_up_score', 'capex_down_score', 
              'competitor_mentions', 'capex_net', 'ai_sentence_ratio']

In [35]:
with_domain_keywords[edgar_cols] = with_domain_keywords[edgar_cols].fillna(0)

In [36]:
with_domain_keywords.to_csv('../../data/ai_sector_features_df.csv')

In [37]:
with_domain_keywords.head()

                     ret_1d    ret_3d    ret_5d   ret_10d   ret_20d    vol_5d  \
Date       Ticker
2019-01-02 NVDA    0.020374  0.038499  0.071923 -0.051261 -0.166493  0.023554
           TSM    -0.010566 -0.007069  0.034854  0.008283 -0.028465  0.020815
           AVGO   -0.003028  0.010604  0.084303  0.008072  0.079068  0.025708
           MRVL    0.019148  0.050955  0.145038  0.086345  0.028352  0.028901
           INTC    0.003196  0.015531  0.080064  0.000000 -0.045224  0.024625

                    vol_20d     rsi_14  rel_soxx   rel_qqq  ...  new_count  \
Date       Ticker                                           ...
2019-01-02 NVDA    0.034328  37.207817 -0.107088 -0.083557  ...        0.0
           TSM     0.017657  49.090054  0.030941  0.054471  ...        0.0
           AVGO    0.026895  58.335414  0.138473  0.162004  ...        0.0
           MRVL    0.030025  64.768889  0.087758  0.111289  ...        0.0
           INTC    0.025632  49.416476  0.014181  0.037712  ...        0.0

                   nvidia_mentions  amd_mentions  intel_mentions  \
Date       Ticker
2019-01-02 NVDA           0.626763           0.0             0.0
           TSM                 NaN           NaN             NaN
           AVGO           0.000000           0.0             0.0
           MRVL                NaN           NaN             NaN
           INTC           0.000000           0.0             0.0

                   gpu_mentions  capex_up_score  capex_down_score  \
Date       Ticker
2019-01-02 NVDA             0.0             0.0               0.0
           TSM              0.0             0.0               0.0
           AVGO             0.0             0.0               0.0
           MRVL             0.0             0.0               0.0
           INTC             0.0             0.0               0.0

                   competitor_mentions  capex_net  ai_sentence_ratio
Date       Ticker
2019-01-02 NVDA                    0.0        0.0           0.000000
           TSM                     0.0        0.0           0.000000
           AVGO                    0.0        0.0           0.000000
           MRVL                    0.0        0.0           0.000000
           INTC                    0.0        0.0           0.003636

[5 rows x 27 columns]

In [38]:
missing = set(all_tickers) - set(transcript_signals_df.index.
    get_level_values('Ticker').unique())
print(missing)
# {'ARM', 'TSM', 'ASML'}

{'ASML', 'TSM', 'ARM'}